version: "3.7"

services:
  app:
    build:
      args:
        user: dominion
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: mts1
    container_name: mts1-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mts1

  db:
    image: mysql:8.0
    # ports:
    #     - 3306:3306
    container_name: mts1-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    #   MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - mts1
  nginx:
    image: nginx:alpine
    container_name: mts1-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - mts1

networks:
  mts1:
    driver: bridge
